# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go vet ./...
  - go fmt ./...
  - go test -coverprofile c.out ./...

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  goos:
  - linux

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
- image_templates:
  - "docker.io/ccremer/zfs-provisioner:v{{ .Version }}"
  - "docker.io/ccremer/zfs-provisioner:v{{ .Major }}"
  - "quay.io/ccremer/zfs-provisioner:v{{ .Version }}"
  - "quay.io/ccremer/zfs-provisioner:v{{ .Major }}"
  extra_files:
  - docker/zfs.sh
  - docker/update-permissions.sh
  dockerfile: docker/Dockerfile

changelog:
  sort: asc
  filters:
    exclude:
    - '^Docs:'
    - '^Test:'
    - '^Refactor:'
    - '^Merge pull request'

release:
  github:
    owner: ccremer
    name: kubernetes-zfs-provisioner
