# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  - go vet ./...
  - go fmt ./...

builds:
- env:
  - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
  goarch:
  - amd64
  - arm64
  goos:
  - linux

archives:
- format: binary
  name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

dockers:
- image_templates:
  - "michaelwoods/zfs-provisioner:v{{ .Version }}"
  - "michaelwoods/zfs-provisioner:v{{ .Major }}"
  extra_files:
  - docker/zfs.sh
  - docker/update-permissions.sh
  dockerfile: docker/Dockerfile
  build_flag_templates:
  - "--build-arg"
  - "ARCH=amd64"
- image_templates:
  - "michaelwoods/zfs-provisioner:v{{ .Version }}"
  - "michaelwoods/zfs-provisioner:v{{ .Major }}"
  extra_files:
  - docker/zfs.sh
  - docker/update-permissions.sh
  goarch: arm64
  dockerfile: docker/Dockerfile
  build_flag_templates:
  - "--build-arg"
  - "ARCH=arm64v8"

docker_manifests:
- name_template: michaelwoods/zfs-provisioner:v{{ .Version }}
  image_templates:
  - "michaelwoods/zfs-provisioner:v{{ .Version }}-amd64"
  - "michaelwoods/zfs-provisioner:v{{ .Version }}-arm64v8"
  - "michaelwoods/zfs-provisioner:v{{ .Major }}-amd64"
  - "michaelwoods/zfs-provisioner:v{{ .Major }}-arm64v8"

changelog:
  sort: asc
  filters:
    exclude:
    - '^Docs:'
    - '^Test:'
    - '^Refactor:'
    - '^Merge pull request'

release:
  github:
    owner: michaelwoods
    name: kubernetes-zfs-provisioner
