{{- if .Values.storageClass.create -}}
{{- range .Values.storageClass.classes }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ .name }}
  labels:
    {{- include "kubernetes-zfs-provisioner.labels" $ | nindent 4 }}
{{- with .annotations }}
  annotations:
    {{ toYaml . | nindent 4 }}
{{- end }}
provisioner: {{ $.Values.provisioner.instance }}
reclaimPolicy: {{ .policy | default "Delete" }}
allowVolumeExpansion: {{ .allowVolumeExpansion | default true }}
volumeBindingMode: {{ .volumeBindingMode | default "Immediate" }}
{{- with .mountOptions }}
mountOptions:
  {{- toYaml . | nindent 2 }}
{{- end }}
parameters:
  parentDataset: {{ .parentDataset | quote }}
  hostname: {{ .hostName | quote }}
  type: {{ .type | default "nfs" | quote }}
  {{- if .node }}
  node: {{ .node | quote }}
  {{- end }}
  {{- if .shareProperties }}
  shareProperties: {{ .shareProperties | quote }}
  {{- end }}
  {{- if kindIs "bool" .reserveSpace }}
  reserveSpace: {{ .reserveSpace | quote }}
  {{- end }}
  {{- if kindIs "bool" .destroySnapshots }}
  destroySnapshots: {{ .destroySnapshots | quote }}
  {{- end }}
{{- end }}
{{- end }}
